### ISSUE TITLE
Model persistence is unsupported

### ISSUE THREAD

**Issue by jjramsey** [amzn/emukit#281]
There doesn't appear to be a way to save fitted models for later use. At least with `multi_fidelity_dgp`, that's a problem. Neither `pickle` nor `dill` are capable of saving an instance of a `MultiFidelityDeepGP` class. There doesn't appear to be a way to save the parameters of the model to be reused later, either

This means that I can't just fit the model in one Python script and use it in later scripts. Fitting and use all have to be in the same session, which is rather limiting.

**Comment by apaleyes** [comment]
Emukit doesn't provide many models itself. Most of the model definitions come out of examples, including the one you mentioned, `MultiFidelityDeepGP`. I don't think it is realistic to expect each example author to implement serialization for their model, especially if they themselves don't need it. The most we, as library authors, can do is to add a few optional methods to `IModel` (e.g. `write_model(file)`, `read_model(file)`) and hope that some users implement them.

That said, most of the models are based on frameworks where serialization can be done. Say for GPy some models can be serialized/deserialized, have a look at their readme for this: https://github.com/SheffieldML/GPy (section "Saving models in a consistent way across versions").

However I don't think every GPy model can be fully deserialized using this technique though. Would you be able to try use it for `MultiFidelityDeepGP` and let us know how it went?

**Comment by jjramsey** [comment]
`MultiFidelityDeepGP` is an Emukit `IModel` that contains a GPFlow model, not a GPy model itself. If I run `print(model.param_array)`, I get the error message "`'MultiFidelityDeepGP' object has no attribute 'param_array'.`" Similarly, If I run `print(model.model.param_array)`, I get the error message "`'DGP_Base' object has no attribute 'param_array'`." (`DGP_Base` inherits from `gpflow.models.model.Model`.)

**Comment by apaleyes** [comment]
Oh, apologies, didn't notice that this one builds on top of GPflow not GPy. Does this thread yield anything helpful? There they discuss `to_dict` which is available, as well as some custom ways users came up with: https://github.com/GPflow/GPflow/issues/48

**Comment by jjramsey** [comment]
Unfortunately, that thread is out of date. Apparently, although they added `get_parameter_dict()`, etc. at one point, that functionality seems to have since been removed. In the GPFlow 1.x series, they did add some [functionality to support model persistence](https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop-1.0/doc/source/notebooks/tips_and_tricks.ipynb#7.-I-want-to-save-and-load-a-GPflow-model), but it doesn't *quite* work.

Suppose that I do the following:

```python
gpflow.saver.Saver().save("foo", model.model)
```

where `model` is a `MultiFidelityDeepGP` and `model.model` is a `DGP_Base`. This will fail with errors like this:

```
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./try-mfdgp.py", line 38, in <module>
    gpflow.saver.Saver().save("foo", model.model)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/saver.py", line 36, in save
    encoded_target = CoderDispatcher(context).encode(target)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 613, in encode
    return self._execute_coder(item, 'encode')
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 606, in _execute_coder
    return coder(self.context).encode(item)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 404, in encode
    data = dispatcher.encode(values)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 613, in encode
    return self._execute_coder(item, 'encode')
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 606, in _execute_coder
    return coder(self.context).encode(item)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 288, in encode
    pre_data = {k : dispatcher.encode(v) for k, v in item.items()}
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 288, in <dictcomp>
    pre_data = {k : dispatcher.encode(v) for k, v in item.items()}
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 613, in encode
    return self._execute_coder(item, 'encode')
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 606, in _execute_coder
    return coder(self.context).encode(item)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 249, in encode
    data = np.array(data, dtype=data_dtype)
ValueError: setting an array element with a sequence.
```

Here, I'm using a version of Tensorflow that's supposed to be compatible with `MultiFidelityDeepGP`, version 1.8, but newer 1.x versions have the same problem. It turns out that GPFlow's `Saver` chokes on the data members `X_list` and `Y_list` of `model.model`. Now if I do the following:

```python
del model.model.X_list
del model.model.Y_list

gpflow.saver.Saver().save("foo", model.model)
```

then I *appear* to have some success--until I try to read the file "foo". This does not work:

```python
import gpflow
import tensorflow as tf

with tf.Graph().as_default(), tf.Session().as_default():
    model = gpflow.saver.Saver().load("foo")
```

This results in the following errors:

```
Traceback (most recent call last):
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 420, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./read-model-mfdgp.py", line 21, in <module>
    model = gpflow.saver.Saver().load("foo")
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/saver.py", line 42, in load
    return CoderDispatcher(context).decode(encoded_target)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 616, in decode
    return self._execute_coder(item, 'decode')
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 608, in _execute_coder
    return coder(self.context).decode(item)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 420, in decode
    return self._decode_object(item, variables)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/saver/coders.py", line 559, in _decode_object
    instance.compile(session=self.context.session)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/core/node.py", line 58, in compile
    self.build()
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/core/node.py", line 156, in build
    self._build()
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/models/model.py", line 79, in _build
    likelihood = self._build_likelihood()
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/emukit/examples/multi_fidelity_dgp/multi_fidelity_deep_gp.py", line 243, in _build_likelihood
    L += (tf.reduce_sum(self.E_log_p_Y(X_l, Y_l, fidelity)) * scale)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/emukit/examples/multi_fidelity_dgp/multi_fidelity_deep_gp.py", line 198, in E_log_p_Y
    Fmean, Fvar = self._build_predict(X_f, full_cov=False, S=self.num_samples, fidelity=fidelity)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/emukit/examples/multi_fidelity_dgp/multi_fidelity_deep_gp.py", line 172, in _build_predict
    _, Fmeans, Fvars = self.propagate(X, full_cov=full_cov, S=S)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/emukit/examples/multi_fidelity_dgp/multi_fidelity_deep_gp.py", line 140, in propagate
    F, Fmean, Fvar = layer.sample_from_conditional(F, z=z, full_cov=full_cov)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/doubly_stochastic_dgp/layers.py", line 88, in sample_from_conditional
    mean, var = self.conditional_SND(X, full_cov=full_cov)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/doubly_stochastic_dgp/layers.py", line 73, in conditional_SND
    mean, var = self.conditional_ND(X_flat)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/doubly_stochastic_dgp/layers.py", line 186, in conditional_ND
    A = tf.matrix_triangular_solve(self.Lu, Kuf, lower=True)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1402, in matrix_triangular_solve
    adjoint=adjoint, name=name)
  File "/Users/jjramsey/venvs/old-tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'matrix' to a tensor and failed. Error: None values not supported.
```

This also fails, and with the same errors:

```python
import gpflow
import tensorflow as tf

ctx_for_loading = gpflow.saver.SaverContext(autocompile=False)
model = gpflow.saver.Saver().load("foo", context=ctx_for_loading)
model.clear()
model.compile()
```

The failure occurs with both Tensorflow 1.8 and later versions as well. With later 1.x versions of Tensorflow, error messages like these are seen as well:

```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'DGP_Base-a6908df1-44/X1/IsVariableInitialized:0' shape=() dtype=bool>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/Users/jjramsey/venvs/emukit_mfdgp/lib/python3.7/site-packages/gpflow/models/model.py", line 79, in _build
    likelihood = self._build_likelihood()  File "/Users/jjramsey/venvs/emukit_mfdgp/lib/python3.7/site-packages/gpflow/params/parameterized.py", line 302, in _build
    self._prior_tensor = self._build_prior(priors)  File "/Users/jjramsey/venvs/emukit_mfdgp/lib/python3.7/site-packages/gpflow/core/node.py", line 156, in build
    self._build()  File "/Users/jjramsey/venvs/emukit_mfdgp/lib/python3.7/site-packages/gpflow/params/dataholders.py", line 91, in _build
    self._is_initialized_tensor = tf.is_variable_initialized(tensor)  File "/Users/jjramsey/venvs/emukit_mfdgp/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
```

**Comment by apaleyes** [comment]
Well, I guess at this point the isue is beyond Emukit's scope. To make sure model can be saved in this example, we would need model persistence in GPflow to work properly, which apparently isn't the case.

I would probably advise to try and raise it with GPflow folks, see if they are aware model persistence isn't working. Sorry we couldn't be of much help here!

**Comment by mmahsereci** [comment]
Thanks, Andrei and jjramsey, I am closing the issue.
